=== PHPBoost/Official/documentation/documentation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT document (header, body)>
    
    <!ELEMENT header (title, authors, dates)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT authors (author+)>
            <!ELEMENT author EMPTY>
            <!ATTLIST author name CDATA #REQUIRED email CDATA #REQUIRED>
        <!ELEMENT dates (creation, last-modification)>
            <!ELEMENT creation (#PCDATA)>
            <!ELEMENT last-modification (#PCDATA)>
        
    <!ELEMENT body (thanks?, content, related?)>
        
        <!ELEMENT text (#PCDATA)>
        <!ELEMENT para (#PCDATA)>
        <!ATTLIST para style CDATA #IMPLIED>
        <!ELEMENT code (line)>
        <!ATTLIST code language CDATA #REQUIRED>
        <!ELEMENT line (#PCDATA)>
        
        <!ELEMENT thanks (text?, thanks-list?)>
        <!ELEMENT thanks-list (thank+)>
        <!ELEMENT thank (#PCDATA)>
        
        <!ELEMENT content (preface?, chapters, appendice?)>
            <!ELEMENT preface (text)>
            <!ELEMENT chapters (chapter+)>
            <!ELEMENT appendice (text)>
            
            <!ELEMENT chapter (chapter|para|code|img)+>
            <!ATTLIST chapter title CDATA #REQUIRED>
            
        <!ELEMENT related (resource+)>
        <!ELEMENT resource (#PCDATA)>

        <!ELEMENT img EMPTY>
        <!ATTLIST img name CDATA #REQUIRED path CDATA #REQUIRED>

=== PHPBoost/Official/documentation/documentation.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "/home/loic/phpboost/documentation/documentation.dtd">
<?xml-stylesheet type="text/xsl" href="documentation.xsl"?>
<document>
    <header>
        <title>Documentation PHPBoost</title>
        <authors>
            <author name="ROUCHON Loïc" email="horn@phpboost.com"/>
            <author name="SAUTEL Benoït" email="ben.popeye@phpboost.com"/>
            <author name="VIARRE Régis" email="crowkait@phpboost.com"/>
        </authors>
        <dates>
            <creation>03/02/2008</creation>
            <last-modification>06/02/2008</last-modification>
        </dates>
    </header>
    <body>
        <thanks>
            <para>Remerciement à tout le monde...</para>
            <thanks-list>
                <thank>Benoit</thank>
                <thank>Loïc</thank>
                <thank>Régis</thank>
            </thanks-list>
        </thanks>
        <content>
            <preface>
                <para>Avant Propos...</para>
            </preface>
            <chapters>
                <chapter title="Utilisation">
                    <chapter title="Installation">
                        <para>Petite image :</para>
                        <img name="PHPBoost" path="../favicon.ico"/>
                        <para>commentaires...</para>
                    </chapter>
                    <para>maintenant, nous allons commencer...</para>
                    <para style="notice">Remarquez ceci...</para>
                    <para style="Warning">Attention...</para>
                    <code language="php">
                        <line>&lt;?php</line>
                        <line>  echo 'Hello World!'</line>
                        <line>?&gt;</line>
                    </code>
                </chapter>
                <chapter title="Développement">
                    <para>
                        Vous trouverez ici la documentation nécessaire pour
                        pouvoir développer un module en se basant sur le noyau PHPBoost.
                    </para>
                    <chapter title="Créer un module additionnel">
                        <para>
                            L'article Créer un module additionnel détaille pas à pas
                            la création d'un module additionnel. Il fait référence aux
                            framework PHPBoost, détaillé dans la partie suivante de
                            cette article. N'hésitez pas à vous y référer régulièrement
                            pour approfondir votre connaissance du framework PHPBoost.
                        </para>
                    </chapter>
                    <chapter title="Framework PHPBoost">
                        <chapter title="Classes">
                            <para>
                                Le framework PHPBoost est composée de classes permettant
                                de faire différentes actions assez simplement pour ne pas
                                avoir à réinventer la roue en développant. Voici la liste
                                de celles qui peuvent être utiles lors du développement d'un
                                module, elles sont classées par importance.
                            </para>
                        </chapter>
                        <chapter title="Fonctions">
                            <para>
                                Le framework PHPBoost contient aussi des fonctions dont
                                l'utilité est très variée.
                            </para>
                        </chapter>
                    </chapter>
                </chapter>
            </chapters>
            <appendice>
                <para>
                    Vous savez donc maintenant comment fonctionne PHPBoost, comment l'utiliser,
                    et aussi comment aider à le développer.
                </para>
                <para>
                    A vous de jouer!!!
                </para>
            </appendice>
        </content>
        <related>
            <link name="PHPBoost - Site Officiel" link="http://www.phpboost.com"/>
            <link name="Documentation Officielle" link="http://www.phpboost.com/wiki/wiki.php"/>
        </related>
    </body>
</document>
